src/BotMonitorMvcClient/ViewComponents/CommandPanel/BotCommandPanelViewComponent.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using BotMonitorMvcClient.Models;
using BotMonitorMvcClient.Utils;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BotMonitorMvcClient.ViewComponents.CommandPanel
{
    public class BotCommandPanelViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {

            //if (string.IsNullOrEmpty(HttpContext.Authentication.GetTokenAsync("access_token").Result))
            //{
            //    return View(new BotCommandModel());
            //}
            //using (var httpClient = new HttpClient())
            //{

            //    var botname = HttpContext.Request.Cookies.GetBotNameOrDefault();
            //    httpClient.BaseAddress = new Uri("http://localhost:60523");
            //    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer",
            //        HttpContext.Authentication.GetTokenAsync("access_token").Result);

            //    var states = await httpClient.GetAsync("api/BotService?botname=" + botname);
            //    var jsonContent =
            //        JsonConvert.DeserializeObject<BotCommandModel>(states.Content.ReadAsStringAsync().Result);

                return View();

           // }
        }
    }
}

src/BotMonitorMvcClient/ViewComponents/DataPanel/BotDataPanelViewComponent.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using BotMonitorMvcClient.Models;
using BotMonitorMvcClient.Utils;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BotMonitorMvcClient.ViewComponents.DataPanel
{
    public class BotDataPanelViewComponent : ViewComponent
    {

        public BotDataPanelViewComponent()
        {
         
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {

            //var token = await HttpContext.Authentication.GetTokenAsync("access_token");
            //using (var httpClient = new HttpClient())
            //{

            //    var botname = HttpContext.Request.Cookies.GetBotNameOrDefault();
            //    httpClient.BaseAddress = new Uri("http://localhost:60523");
            //    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);

            //    var states = await httpClient.GetAsync("api/Districs?botname=" + botname);
            //    var jsonContent = JsonConvert.DeserializeObject<List<DistrictTableModel>>(await states.Content.ReadAsStringAsync());

                return View();
            
          
        }
    }
}

src/BotMonitorMvcClient/ViewComponents/DataPanel/DistrictDataPanelViewComponent.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using BotMonitorMvcClient.Models;
using BotMonitorMvcClient.Utils;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BotMonitorMvcClient.ViewComponents.DataPanel
{
    public class DistrictDataPanelViewComponent : ViewComponent
    {

        public DistrictDataPanelViewComponent()
        {
         
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            //if (string.IsNullOrEmpty(HttpContext.Authentication.GetTokenAsync("access_token").Result))
            //{
            //    return View(new SessionTableModel());
            //}

            //using (var httpClient = new HttpClient())
            //{

            //    var botname = HttpContext.Request.Cookies.GetBotNameOrDefault();
            //    var districtName = HttpContext.Request.Cookies.GetDistrictNameOrDefault();
            //    httpClient.BaseAddress = new Uri("http://localhost:60523");
            //    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Authentication.GetTokenAsync("access_token").Result);

            //    var states = await httpClient.GetAsync($"api/Session?botname={botname}&district={districtName}");
            //    var jsonContent = JsonConvert.DeserializeObject<List<SessionTableModel>>(states.Content.ReadAsStringAsync().Result);

                return View();
            //}
        }
    }
}

src/BotMonitorMvcClient/ViewComponents/DataPanel/SessionDataPanelViewComponent.cs
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using BotMonitorMvcClient.Models;
using BotMonitorMvcClient.Utils;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using NuGet.ProjectModel;

namespace BotMonitorMvcClient.ViewComponents.DataPanel
{
    public class SessionDataPanelViewComponent : ViewComponent
    {

        public async Task<IViewComponentResult> InvokeAsync()
        {
           
            //if (string.IsNullOrEmpty(HttpContext.Authentication.GetTokenAsync("access_token").Result))
            //{
            //    return View(new List<SessionTableModel>());
            //}
            //using (var httpClient = new HttpClient())
            //{

            //  var botname = HttpContext.Request.Cookies.GetBotNameOrDefault();
            //    var districtName = HttpContext.Request.Cookies.GetDistrictNameOrDefault();
            //    var sessionId = HttpContext.Request.Cookies.GetSession();
            //    if (string.IsNullOrEmpty(sessionId))
            //    {
            //        return View("Default", new SessionTabModel()
            //        {
            //            Location = "Session do not choose",
            //            Level = 777,
            //            TimeLeft = 2000
                                             
            //        });
            //    }
            //    httpClient.BaseAddress = new Uri("http://localhost:60523");
            //    httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", HttpContext.Authentication.GetTokenAsync("access_token").Result);

            //    SessionTabModel sessionTabModel = new SessionTabModel();
            //    //Запрос игровой информации
            //    var gameState = await httpClient.GetAsync($"api/GameInfo/{sessionId}?botname=exilebuddy");
            //    var jsonGameState = JObject.Parse(gameState.Content.ReadAsStringAsync().Result);
            //    //Заполнение игровой информации
            //    sessionTabModel.Level = jsonGameState["CurrentLevel"].ToObject<int>();
            //    sessionTabModel.Location = jsonGameState["CurrentAreaName"].ToObject<string>();
            //    sessionTabModel.CharName = jsonGameState["CharName"].ToObject<string>();


            //    foreach (var VARIABLE in jsonGameState["ValuableCurrency"].Children())
            //    {
            //        sessionTabModel.CurrencyTableModels.Add(JsonConvert.DeserializeObject<CurrencyTableModel>(VARIABLE.ToString()));
            //    }

            //    //Запрос информации о состоянии ботагента

            //    var botAgentState = await httpClient.GetAsync($"api/Session/{sessionId}?botname={botname}&district={districtName}");
            //    var jsonContent = JsonConvert.DeserializeObject<SessionTableModel>(botAgentState.Content.ReadAsStringAsync().Result);

            //    if (jsonContent != null)
            //    {
            //        sessionTabModel.TimeLeft = jsonContent.TimeLeft;
            //        return View("Default", sessionTabModel);
            //    }
            //    else
            //    {
                    return View();
                }
            //}
          
        //}
    }
}

src/BotMonitorMvcClient/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

src/BotMonitorMvcClient/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/BotMonitorMvcClient/Views/Home/Index.cshtml
@using System.ComponentModel

        <ul class="uk-tab" data-uk-tab="{connect:'#my-id'}">
            <li id="botTab"><a href="">Bot</a></li>
            <li id="districtTab"><a href="" >District</a></li>
            <li id="sessionTab"><a href="" >Session</a></li>
        </ul>

        <ul id="my-id" class="uk-switcher uk-margin">
            <li>
                <div class="uk-grid">
                    <div class="uk-width-2-3" >
                        @await Component.InvokeAsync("BotDataPanel")
                    </div>
                    <div class="uk-width-1-3">
                        @await Component.InvokeAsync("BotCommandPanel")
                        
                    </div>
                              
                </div>

            </li>
            <li>
                <div class="uk-grid">
                    <div class="uk-width-2-3">                      
                       @await Component.InvokeAsync("DistrictDataPanel")

                    </div>
                    <div class="uk-width-1-3">
                        @await Component.InvokeAsync("DistrictCommandPanel")
                    </div>
                   

                </div>
            </li>
            <li>
                <div class="uk-grid">
                    <div class="uk-width-2-3" >
                        @await Component.InvokeAsync("SessionDataPanel")

                    </div>
                    <div class="uk-width-1-3" >
                        @await Component.InvokeAsync("SessionCommandPanel")
                    </div>

                </div>
            </li>
        </ul>